// src/components/RightSidebar/TableOfContents.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import type { MarkdownHeading } from "astro";

    export let headings: MarkdownHeading[];

    type ItemOffset = {
        id: string,
        topOffset: number
    };

    let scrollY: number;
    let titles: NodeListOf<Element>;
    let itemOffsets: ItemOffset[];

    onMount(() => {
        titles = document.querySelectorAll('article :is(h1, h2, h3, h4, h5, h6)');
        itemOffsets = Array.from(titles).map(title => ({
            id: title.id,
            topOffset: title.getBoundingClientRect().top + window.scrollY
        }));
    })
</script>

<svelte:window bind:scrollY={scrollY} />

<h2 class="heading">On this page</h2>
<ol>
    <li class="heading-link">
        <a href="#overview">
            Overview
        </a>
    </li>
    {#each headings as heading}
        <li class="heading-link depth-{heading.depth}"
            class:active={
                (itemOffsets ?? []).at(
                    (itemOffsets ?? []).lastIndexOf(
                        (itemOffsets ?? []).filter(
                            (entry) => entry.topOffset <= scrollY
                        ).at(-1) ?? { id: '', topOffset: -1 }
                    ) + 1
                )?.id === heading.slug}
        >
            <a href="#{heading.slug}">
                {heading.text}
            </a>
        </li>
    {/each}
</ol>

<style>
    li {
        border-left: 4px solid transparent;
        padding-right: 2em;
    }
    .active {
        border-left: 4px solid var(--color-blue-dark);
        background-color: var(--color-blue-light);
    }
    li:hover:not(.active) {
        border-left: 4px solid var(--color-blue-light);
        background-color: var(--color-blue-xlight);
    }
</style>

// src/components/RightSidebar/TableOfContents.tsx
import type { FunctionalComponent } from 'preact';
import { useState, useEffect, useRef } from 'preact/hooks';
import type { MarkdownHeading } from 'astro';

type ItemOffsets = {
	id: string;
	topOffset: number;
};

const TableOfContents: FunctionalComponent<{ headings: MarkdownHeading[] }> = ({
	headings = [],
}) => {
	const itemOffsets = useRef<ItemOffsets[]>([]);
	// FIXME: Not sure what this state is doing. It was never set to anything truthy.
	const [activeId] = useState<string>('');
	useEffect(() => {
		const getItemOffsets = () => {
			const titles = document.querySelectorAll('article :is(h1, h2, h3, h4)');
			itemOffsets.current = Array.from(titles).map((title) => ({
				id: title.id,
				topOffset: title.getBoundingClientRect().top + window.scrollY,
			}));
		};

		getItemOffsets();
		window.addEventListener('resize', getItemOffsets);

		return () => {
			window.removeEventListener('resize', getItemOffsets);
		};
	}, []);

	return (
		<>
			<h2 className="heading">On this page</h2>
			<ul>
				<li className={`heading-link depth-2 ${activeId === 'overview' ? 'active' : ''}`.trim()}>
					<a href="#overview">
						<p tabIndex={0}>Overview</p>
					</a>
				</li>
				{headings
					.filter(({ depth }) => depth > 1 && depth < 4)
					.map((heading) => (
						<li
							className={`heading-link depth-${heading.depth} ${
								activeId === heading.slug ? 'active' : ''
							}`.trim()}
						>
							<a href={`#${heading.slug}`}>
								<p tabIndex={0}>{heading.text}</p>
							</a>
						</li>
					))}
			</ul>
		</>
	);
};

export default TableOfContents;
